### ISSUE TITLE
在哪个位置把开始编号调成从二级开始呀？css里面不太好找

### ISSUE THREAD

**Issue by Swinden** [MadMaxChow/VLOOK#111]
```css
/**
 * author: LPZ
 * email: lpzmail@163.com
 */

h1, h2, h3, h4, strong {
  font-weight: 600;
}

/* 添加自动序号样式 */
#write {
  counter-reset: h2;
}

h1 {
  counter-reset: h2;
}

h2 {
  counter-reset: h3;
}

h3 {
  counter-reset: h4;
}

h4 {
  counter-reset: h5;
}

h5 {
  counter-reset: h6;
}

#write h2:before {
  counter-increment: h2;
  content: counter(h2) ". ";
}

#write h3:before,
h3.md-focus.md-heading:before { /** override the default style for focused headings */
  counter-increment: h3;
  content: counter(h2) "."counter(h3) ". ";
}

#write h4:before,
h4.md-focus.md-heading:before {
  counter-increment: h4;
  content: counter(h2) "."counter(h3) "."counter(h4) ". ";
}

#write h5:before,
h5.md-focus.md-heading:before {
  counter-increment: h5;
  content: counter(h2) "."counter(h3) "."counter(h4) "."counter(h5) ". "
}

#write h6:before,
h6.md-focus.md-heading:before {
  counter-increment: h6;
  content: counter(h2) "."counter(h3) "."counter(h4) "."counter(h5) "."counter(h6) ". "
}

/** override the default style for focused headings */
#write>h3.md-focus:before,
#write>h4.md-focus:before,
#write>h5.md-focus:before,
#write>h6.md-focus:before,
h3.md-focus:before,
h4.md-focus:before,
h5.md-focus:before,
h6.md-focus:before {
  color: inherit;
  border: inherit;
  border-radius: inherit;
  position: inherit;
  left: initial;
  float: none;
  top: initial;
  font-size: inherit;
  padding-left: inherit;
  padding-right: inherit;
  vertical-align: inherit;
  font-weight: inherit;
  line-height: inherit;
}

/* 自定义强制换号符，使得在导出PDF 或打印时强制换行 */
@media print {

  /* 这是自定义标签, 在需要换行的地方插入：<pb> */
  pb {
    display: block;
    page-break-after: always;
  }

  h1 {
    page-break-before: always;
  }

  h1:first-of-type {
    page-break-before: avoid;
  }
}

/* 完成的 Task 添加删除线 */
.task-list-done {
  text-decoration: line-through;
  color: #777;
}

.task-list-not-done {}

/* 添加键盘样式 */
kbd {
  box-shadow: inset 0 -2px 0 #c6cbd1;
  background-color: white;
}

/* TOC 中隐藏 H1 和 H6 */
.md-toc-h1, .md-toc-h6 {
  display: none;
}

/* 添加 TOC 自动序号样式 */
.md-toc-content {
  counter-reset: toc-h2;
}

.md-toc-h1 {
  counter-reset: toc-h2;
}

.md-toc-h2 {
  counter-reset: toc-h3;
}

.md-toc-h3 {
  counter-reset: toc-h4;
}

.md-toc-h4 {
  counter-reset: toc-h5;
}

.md-toc-h5 {
  counter-reset: toc-h6;
}

.md-toc-content .md-toc-h2 a:before {
  counter-increment: toc-h2;
  content: counter(toc-h2) ". ";
}

.md-toc-content .md-toc-h3 a:before {
  counter-increment: toc-h3;
  content: counter(toc-h2) "."counter(toc-h3) ". ";
}

.md-toc-content .md-toc-h4 a:before {
  counter-increment: toc-h4;
  content: counter(toc-h2) "."counter(toc-h3) "."counter(toc-h4) ". ";
}

.md-toc-content .md-toc-h5 a:before {
  counter-increment: toc-h5;
  content: counter(toc-h2) "."counter(toc-h3) "."counter(toc-h4) "."counter(toc-h5) ". ";
}

.md-toc-content .md-toc-h6 a:before {
  counter-increment: toc-h6;
  content: counter(toc-h2) "."counter(toc-h3) "."counter(toc-h4) "."counter(toc-h5) "."counter(toc-h6) ". ";
}

/* 侧边栏自动编号 */
.outline-content {
  counter-reset: outline-h2;
}

.outline-h1 {
  counter-reset: outline-h2;
}

.outline-h2 {
  counter-reset: outline-h3;
}

.outline-h3 {
  counter-reset: outline-h4;
}

.outline-h4 {
  counter-reset: outline-h5;
}

.outline-h5 {
  counter-reset: outline-h6;
}

.outline-content .outline-h2 .outline-label:before {
  counter-increment: outline-h2;
  content: counter(outline-h2) ". ";
}

.outline-content .outline-h3 .outline-label:before {
  counter-increment: outline-h3;
  content: counter(outline-h2) "."counter(outline-h3) ". ";
}

.outline-content .outline-h4 .outline-label:before {
  counter-increment: outline-h4;
  content: counter(outline-h2) "."counter(outline-h3) "."counter(outline-h4) ". ";
}

.outline-content .outline-h5 .outline-label:before {
  counter-increment: outline-h5;
  content: counter(outline-h2) "."counter(outline-h3) "."counter(outline-h4) "."counter(outline-h5) ". ";
}

.outline-content .outline-h6 .outline-label:before {
  counter-increment: outline-h6;
  content: counter(outline-h2) "."counter(outline-h3) "."counter(outline-h4) "."counter(outline-h5) "."counter(outline-h6) ". ";
}
```
知道改这个，toc和侧边栏，改到了，就是标题改成接着toc的整数开始编了
