### ISSUE TITLE
主题配色支持CSS的「::selection」

### ISSUE THREAD

**Issue by MadMaxChow** [MadMaxChow/VLOOK#28]
不同时间使用指定的选中文本颜色、背景色，以使视觉效果更协调。
```CSS
::selection {
    background:#d3d3d3; 
    color:#555;
}

::-moz-selection {
    background:#d3d3d3; 
    color:#555;
}

::-webkit-selection {
    background:#d3d3d3; 
    color:#555;
}
```
